# SPDX-FileCopyrightText: 2026 iurFRIEND and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: Lint php-cs

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lint-php-cs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    name: php-cs

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get php version
        id: versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2

      - name: Set up php ${{ steps.versions.outputs.php-min }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ steps.versions.outputs.php-min }}
          extensions: ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, session, simplexml, xmlreader, xmlwriter, zip, zlib
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Lint
        run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )
