# SPDX-FileCopyrightText: 2026 iurFRIEND and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: phpunit-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      php-min: ${{ steps.versions.outputs.php-min }}
      php-max: ${{ steps.versions.outputs.php-max }}
    steps:
      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2

  phpunit:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        php-versions: ['${{ needs.matrix.outputs.php-min }}', '${{ needs.matrix.outputs.php-max }}']

    name: phpunit php${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, session, simplexml, xmlreader, xmlwriter, zip, zlib
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --ignore-platform-req=php+

      - name: Run unit tests
        run: composer run test:unit
